# Generated by Django 5.2.6 on 2025-11-25 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(help_text='Código de barras universal (EAN)', max_length=13, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_produto', models.CharField(choices=[('UNITARIO', 'Produto Unitário'), ('PESAVEL', 'Produto Pesável')], default='UNITARIO', max_length=10)),
                ('esta_ativo', models.BooleanField(default=True, help_text='Indica se o produto está ativo no catálogo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produto.categoria')),
            ],
        ),
    ]
