# Generated by Django 5.2.6 on 2025-11-25 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('produto', '0001_initial'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filial.filial'),
        ),
    ]
