# Generated by Django 5.2.6 on 2025-11-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id_auth', models.IntegerField(help_text='ID do usuário no serviço de Autenticação', unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('OPERADOR', 'Operador de Caixa')], default='GERENTE', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial')),
            ],
        ),
    ]
